# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/anthonyrivera/CLionProjects/untitled9

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/anthonyrivera/CLionProjects/untitled9

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/anthonyrivera/CLionProjects/untitled9/CMakeFiles /Users/anthonyrivera/CLionProjects/untitled9//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/anthonyrivera/CLionProjects/untitled9/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MySQLConnectorExample

# Build rule for target.
MySQLConnectorExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MySQLConnectorExample
.PHONY : MySQLConnectorExample

# fast build rule for target.
MySQLConnectorExample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/build
.PHONY : MySQLConnectorExample/fast

#=============================================================================
# Target rules for targets named MySQLConnectorExample_autogen_timestamp_deps

# Build rule for target.
MySQLConnectorExample_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MySQLConnectorExample_autogen_timestamp_deps
.PHONY : MySQLConnectorExample_autogen_timestamp_deps

# fast build rule for target.
MySQLConnectorExample_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample_autogen_timestamp_deps.dir/build.make CMakeFiles/MySQLConnectorExample_autogen_timestamp_deps.dir/build
.PHONY : MySQLConnectorExample_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named MySQLConnectorExample_autogen

# Build rule for target.
MySQLConnectorExample_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MySQLConnectorExample_autogen
.PHONY : MySQLConnectorExample_autogen

# fast build rule for target.
MySQLConnectorExample_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample_autogen.dir/build.make CMakeFiles/MySQLConnectorExample_autogen.dir/build
.PHONY : MySQLConnectorExample_autogen/fast

AddCustomerWidget.o: AddCustomerWidget.cpp.o
.PHONY : AddCustomerWidget.o

# target to build an object file
AddCustomerWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/AddCustomerWidget.cpp.o
.PHONY : AddCustomerWidget.cpp.o

AddCustomerWidget.i: AddCustomerWidget.cpp.i
.PHONY : AddCustomerWidget.i

# target to preprocess a source file
AddCustomerWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/AddCustomerWidget.cpp.i
.PHONY : AddCustomerWidget.cpp.i

AddCustomerWidget.s: AddCustomerWidget.cpp.s
.PHONY : AddCustomerWidget.s

# target to generate assembly for a file
AddCustomerWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/AddCustomerWidget.cpp.s
.PHONY : AddCustomerWidget.cpp.s

CustomerData.o: CustomerData.cpp.o
.PHONY : CustomerData.o

# target to build an object file
CustomerData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/CustomerData.cpp.o
.PHONY : CustomerData.cpp.o

CustomerData.i: CustomerData.cpp.i
.PHONY : CustomerData.i

# target to preprocess a source file
CustomerData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/CustomerData.cpp.i
.PHONY : CustomerData.cpp.i

CustomerData.s: CustomerData.cpp.s
.PHONY : CustomerData.s

# target to generate assembly for a file
CustomerData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/CustomerData.cpp.s
.PHONY : CustomerData.cpp.s

MainWindow.o: MainWindow.cpp.o
.PHONY : MainWindow.o

# target to build an object file
MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/MainWindow.cpp.o
.PHONY : MainWindow.cpp.o

MainWindow.i: MainWindow.cpp.i
.PHONY : MainWindow.i

# target to preprocess a source file
MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/MainWindow.cpp.i
.PHONY : MainWindow.cpp.i

MainWindow.s: MainWindow.cpp.s
.PHONY : MainWindow.s

# target to generate assembly for a file
MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/MainWindow.cpp.s
.PHONY : MainWindow.cpp.s

ModifyCustomerWidget.o: ModifyCustomerWidget.cpp.o
.PHONY : ModifyCustomerWidget.o

# target to build an object file
ModifyCustomerWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/ModifyCustomerWidget.cpp.o
.PHONY : ModifyCustomerWidget.cpp.o

ModifyCustomerWidget.i: ModifyCustomerWidget.cpp.i
.PHONY : ModifyCustomerWidget.i

# target to preprocess a source file
ModifyCustomerWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/ModifyCustomerWidget.cpp.i
.PHONY : ModifyCustomerWidget.cpp.i

ModifyCustomerWidget.s: ModifyCustomerWidget.cpp.s
.PHONY : ModifyCustomerWidget.s

# target to generate assembly for a file
ModifyCustomerWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/ModifyCustomerWidget.cpp.s
.PHONY : ModifyCustomerWidget.cpp.s

MySQLConnectorExample_autogen/mocs_compilation.o: MySQLConnectorExample_autogen/mocs_compilation.cpp.o
.PHONY : MySQLConnectorExample_autogen/mocs_compilation.o

# target to build an object file
MySQLConnectorExample_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/MySQLConnectorExample_autogen/mocs_compilation.cpp.o
.PHONY : MySQLConnectorExample_autogen/mocs_compilation.cpp.o

MySQLConnectorExample_autogen/mocs_compilation.i: MySQLConnectorExample_autogen/mocs_compilation.cpp.i
.PHONY : MySQLConnectorExample_autogen/mocs_compilation.i

# target to preprocess a source file
MySQLConnectorExample_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/MySQLConnectorExample_autogen/mocs_compilation.cpp.i
.PHONY : MySQLConnectorExample_autogen/mocs_compilation.cpp.i

MySQLConnectorExample_autogen/mocs_compilation.s: MySQLConnectorExample_autogen/mocs_compilation.cpp.s
.PHONY : MySQLConnectorExample_autogen/mocs_compilation.s

# target to generate assembly for a file
MySQLConnectorExample_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/MySQLConnectorExample_autogen/mocs_compilation.cpp.s
.PHONY : MySQLConnectorExample_autogen/mocs_compilation.cpp.s

SearchViewCustomerWidget.o: SearchViewCustomerWidget.cpp.o
.PHONY : SearchViewCustomerWidget.o

# target to build an object file
SearchViewCustomerWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/SearchViewCustomerWidget.cpp.o
.PHONY : SearchViewCustomerWidget.cpp.o

SearchViewCustomerWidget.i: SearchViewCustomerWidget.cpp.i
.PHONY : SearchViewCustomerWidget.i

# target to preprocess a source file
SearchViewCustomerWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/SearchViewCustomerWidget.cpp.i
.PHONY : SearchViewCustomerWidget.cpp.i

SearchViewCustomerWidget.s: SearchViewCustomerWidget.cpp.s
.PHONY : SearchViewCustomerWidget.s

# target to generate assembly for a file
SearchViewCustomerWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/SearchViewCustomerWidget.cpp.s
.PHONY : SearchViewCustomerWidget.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySQLConnectorExample.dir/build.make CMakeFiles/MySQLConnectorExample.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MySQLConnectorExample_autogen"
	@echo "... MySQLConnectorExample_autogen_timestamp_deps"
	@echo "... MySQLConnectorExample"
	@echo "... AddCustomerWidget.o"
	@echo "... AddCustomerWidget.i"
	@echo "... AddCustomerWidget.s"
	@echo "... CustomerData.o"
	@echo "... CustomerData.i"
	@echo "... CustomerData.s"
	@echo "... MainWindow.o"
	@echo "... MainWindow.i"
	@echo "... MainWindow.s"
	@echo "... ModifyCustomerWidget.o"
	@echo "... ModifyCustomerWidget.i"
	@echo "... ModifyCustomerWidget.s"
	@echo "... MySQLConnectorExample_autogen/mocs_compilation.o"
	@echo "... MySQLConnectorExample_autogen/mocs_compilation.i"
	@echo "... MySQLConnectorExample_autogen/mocs_compilation.s"
	@echo "... SearchViewCustomerWidget.o"
	@echo "... SearchViewCustomerWidget.i"
	@echo "... SearchViewCustomerWidget.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

